App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [

    url(r'^register/',views.register,name='register'),


]

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [

    url(r'^index/',views.index,name='index'),
    url(r'^content/(\d+)$',views.content,name='content'),
    url(r'^content/(\d+)/(\d+)$',views.content,name='content'),
    url(r'^publish/$',views.publish,name='publish'),
    url(r'^search/$',views.search,name='search'),
    url(r'^publish/(\d+)/$',views.publish,name='publish'),
    url(r'^sort_article/$',views.sort_article,name='sort_article'),

]

football/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('App.urls',namespace='user')),
    url(r'^blog/',include('blog.urls',namespace='blog')),


]

App/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):

    class Meta(AbstractUser.Meta):
        pass

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

# 文章
class Article(models.Model):

    author = models.CharField(max_length=16)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=2000)
    # create_time = models.DateTimeField(default=timezone.now,)
    create_time = models.DateTimeField(auto_now=True)

    @classmethod
    def publish_article(cls, author, title, content):
        art = cls(author=author, title=title, content=content)
        return art

    class Meta:
        ordering = ['-create_time']

# 评论
class BlogComment(models.Model):
    username = models.CharField(max_length=16)
    article = models.ForeignKey(Article)
    comment = models.TextField(max_length=1000)
    parent = models.ForeignKey('self',default=None,blank=True,null=True)
    # create_time = models.DateTimeField(default=timezone.now)
    create_time = models.DateTimeField(auto_now=True)


    @classmethod
    def comment_text(cls, username, article, comment, parent):
        com = cls(username=username, article=article, parent=parent, comment=comment)
        return com
    class Meta:
        ordering = ['-create_time']

App/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from App.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(min_length=6, max_length=32)
    # password1 = forms.CharField(min_length=6, max_length=16)
    # password2 = forms.CharField(required=False)
    class Meta(UserCreationForm.Meta):
        model = User
        filter = ('username','email')

blog/forms.py
from django import forms
from django.forms import IntegerField,Textarea,CharField,DateField,ChoiceField


# 发表，编辑表单
class PublishForm(forms.Form):
    aid = forms.IntegerField()
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)

App/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect

from .forms import RegisterForm
# Create your views here.


@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('hahahhahahaha')
        else:
            return HttpResponse('??????')
    else:
        form = RegisterForm()
        context = {
            'form':form,
        }
        return render(request,'users/register.html',context)

blog/views.py
import random
import math
import redis
import logging
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from django.core.cache import cache
from blog.models import Article,BlogComment
from blog.forms import PublishForm
from .helper import statistic,page_cache,page_cache_two,read_counter

# 页面缓存装饰器
from django.views.decorators.cache import cache_page
# Create your views here.

r = redis.Redis()
# blog 首页
def index(request):
    # 分页
    articles_list = Article.objects.all()
    paginator = Paginator(articles_list, 5)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        articles = paginator.page(1)
    pages_range=range(1,articles.paginator.num_pages+1)


    # 分页的另一种
    # pages = math.ceil(Article.objects.count() / 5)  # 页码数
    # page = int(request.GET.get('page', 1))
    # page = (page - 1) if 1 <= page <= pages else 0
    # start = page * 5
    # end = (page + 1) * 5
    # articles = Article.objects.all()[start:end]
    # pages_range=range(1,pages+1)
    context = {'articles':articles,'pages_range':pages_range}
    return render(request, 'blog/index.html', context)





# 文章详情页
@statistic   #日志打印
@read_counter   #统计点击次数
# @page_cache   #自己的页面缓存
# @page_cache_two(100)   #自己页面缓存
# @cache_page(60)  #页面缓存装饰器  参数为过期时间  单位秒
def content(request,*args, **kwargs):

    # 不使用装饰器的页面缓存
    article = cache.get('article'+str(args[0]))
    if article is None:
        article = Article.objects.filter(id=args[0]).first()
        cache.set('article'+str(args[0]),article,)

    # article = Article.objects.filter(id=args[0]).first()
    # redis统计点击次数，不使用装饰器
    # key = 'sort_article'
    # r.zincrby(key,str(args[0]))  #自加一


    if request.method == 'POST':
        num = random.randint(1,99999)
        username = '游客'+str(num)
        comment = request.POST.get('comment')
        # 判断是否输入空
        if comment != '':
            # 判断是否有父评论
            if len(args) > 1:
                parent = BlogComment.objects.filter(id = args[1]).first()
            else:
                parent = None
            com = BlogComment.comment_text(username, article, comment, parent)
            com.save()
    comments = BlogComment.objects.filter(article=article)
    context = {'article':article,'comments':comments}
    return render(request,'blog/content.html',context)


# 文章标题搜索
def search(request):
    q = request.GET.get('sreach')
    if not q:
        return HttpResponseRedirect(reverse('blog:index'))

    articles = Article.objects.filter(title__icontains=q)
    context = {'articles':articles}
    return render(request, 'blog/index.html', context)


# 编辑，发表
def publish(request,*args):
    if request.method == 'POST':
        # print('____________________________________________________')
        form = PublishForm(request.POST)
        if form.is_valid():
            aid = form.cleaned_data['aid']
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']

            article = Article.objects.get(id=aid)
            article.title = title
            article.content = content

            article.save()

            return HttpResponseRedirect(reverse('blog:index'))
        # 发表文章的提交
        else:
            author = '作者'+str(random.randint(1,99999))
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']

            art = Article.publish_article(author,title,content)
            art.save()
            return HttpResponseRedirect(reverse('blog:index'))
    else:
        if len(args) == 0:
            context = {}
            return render(request, 'blog/publish.html', context)
        article = Article.objects.get(id=args[0])
        context = {'article':article}
        return render(request, 'blog/publish.html', context)


# 文章点击量排序
def sort_article(request):
    key = 'sort_article'
    r.zrevrange(key,0,10)
        #去除前十的文章id，和访次数
    a_list = [(int(aid),int(count)) for aid,count in r.zrevrange(key, 0, 10, withscores=True)]
    # 文章id  按访问量排序的
    aid_list = [aid[0] for aid in a_list]
    print(aid_list)
    # 取出文章对象的 队列  不是按照访问量进行排序的
    articles_list = Article.objects.filter(id__in=aid_list)
    # 将文章id与文章对象，写入字典，不是按照访问量进行排序的
    articles_dict = {article.id: article for article in articles_list}
    # 按照排好序的id  取出文章对象
    articles = [articles_dict[aid] for aid in aid_list]
    context = {'articles': articles}
    return render(request, 'blog/index.html', context)


    '''测试'''
    # 取出文章对象  跟访问量
    # article_count = [(articles_dict[aid],count) for aid,count in a_list]
    # return render(request, 'blog/sort.html', {'article_count':article_count})

templates/base.html
{% load static %}
<!doctype html>
{#{% static 'css/layouts/blog.css' %}#}
<html lang="en">
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a blog page with a list of posts.">
    <script type="text/javascript" src={% static 'js/jquery.min.js' %}></script>
    <script type="text/javascript" src={% static 'js/bootstrap.js' %}></script>

    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->


        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/layouts/blog-old-ie.css">
        <![endif]-->
        <!--[if gt IE 8]><!-->
            <link rel="stylesheet" href="{% static 'css/layouts/blog.css' %}">
        <!--<![endif]-->

    {% block personResource %}

    {% endblock %}
</head>
<body>








<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header" >
            <h1 class="brand-title">A Sample Blog</h1>
            <h2 class="brand-tagline">Creating a blog layout using Pure</h2>

            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'blog:index' %}">Blog List</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'blog:publish' %}">Publish Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'blog:sort_article' %}">Sort Blog</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div >
        <div style="margin-bottom: 50px!important;">
        <form class="pure-form" action="{% url 'blog:search' %}"  >
    {%csrf_token%}
    <input class="pure-input-2-3" type="text" name="sreach"  placeholder="">

        <button type="submit" class="pure-button pure-button-primary">搜索</button>

 </form>

        </div>
            {% block content %}

            {% endblock %}

            <!-- A wrapper for all the blog posts -->
{#            <div class="posts">#}
{#                <h1 class="content-subhead">Pinned Post</h1>#}
{##}
{#                <!-- A single blog post -->#}
{#                <section class="post">#}
{#                    <header class="post-header">#}
{#                        <img width="48" height="48" alt="Tilo Mitra&#x27;s avatar" class="post-avatar" src="img/common/tilo-avatar.png">#}
{##}
{#                        <h2 class="post-title">Introducing Pure</h2>#}
{##}
{#                        <p class="post-meta">#}
{#                            By <a href="#" class="post-author">Tilo Mitra</a> under <a class="post-category post-category-design" href="#">CSS</a> <a class="post-category post-category-pure" href="#">Pure</a>#}
{#                        </p>#}
{#                    </header>#}
{##}
{#                    <div class="post-description">#}
{#                        <p>#}
{#                            Yesterday at CSSConf, we launched Pure – a new CSS library. Phew! Here are the <a href="https://speakerdeck.com/tilomitra/pure-bliss">slides from the presentation</a>. Although it looks pretty minimalist, we’ve been working on Pure for several months. After many iterations, we have released Pure as a set of small, responsive, CSS modules that you can use in every web project.#}
{#                        </p>#}
{#                    </div>#}
{#                </section>#}
{#            </div>#}

{#            <div class="posts">#}
{#                <h1 class="content-subhead">Recent Posts</h1>#}

{#                <section class="post">#}
{#                    <header class="post-header">#}
{#                        <img width="48" height="48" alt="Eric Ferraiuolo&#x27;s avatar" class="post-avatar" src="img/common/ericf-avatar.png">#}
{##}
{#                        <h2 class="post-title">Everything You Need to Know About Grunt</h2>#}
{##}
{#                        <p class="post-meta">#}
{#                            By <a class="post-author" href="#">Eric Ferraiuolo</a> under <a class="post-category post-category-js" href="#">JavaScript</a>#}
{#                        </p>#}
{#                    </header>#}
{##}
{#                    <div class="post-description">#}
{#                        <p>#}
{#                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.#}
{#                        </p>#}
{#                    </div>#}
{#                </section>#}

{#                <section class="post">#}
{#                    <header class="post-header">#}
{#                        <img width="48" height="48" alt="Reid Burke&#x27;s avatar" class="post-avatar" src="img/common/reid-avatar.png">#}
{##}
{#                        <h2 class="post-title">Photos from CSSConf and JSConf</h2>#}
{##}
{#                        <p class="post-meta">#}
{#                            By <a class="post-author" href="#">Reid Burke</a> under <a class="post-category" href="#">Uncategorized</a>#}
{#                        </p>#}
{#                    </header>#}
{##}
{#                    <div class="post-description">#}
{#                        <div class="post-images pure-g">#}
{#                            <div class="pure-u-1 pure-u-md-1-2">#}
{#                                <a href="http://www.flickr.com/photos/uberlife/8915936174/">#}
{#                                    <img alt="Photo of someone working poolside at a resort"#}
{#                                         class="pure-img-responsive"#}
{#                                         src="http://farm8.staticflickr.com/7448/8915936174_8d54ec76c6.jpg">#}
{#                                </a>#}
{##}
{#                                <div class="post-image-meta">#}
{#                                    <h3>CSSConf Photos</h3>#}
{#                                </div>#}
{#                            </div>#}
{##}
{#                            <div class="pure-u-1 pure-u-md-1-2">#}
{#                                <a href="http://www.flickr.com/photos/uberlife/8907351301/">#}
{#                                    <img alt="Photo of the sunset on the beach"#}
{#                                         class="pure-img-responsive"#}
{#                                         src="http://farm8.staticflickr.com/7382/8907351301_bd7460cffb.jpg">#}
{#                                </a>#}
{##}
{#                                <div class="post-image-meta">#}
{#                                    <h3>JSConf Photos</h3>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </section>#}

{#                <section class="post">#}
{#                    <header class="post-header">#}
{#                        <img width="48" height="48" alt="Andrew Wooldridge&#x27;s avatar" class="post-avatar" src="img/common/andrew-avatar.png">#}
{##}
{#                        <h2 class="post-title">YUI 3.10.2 Released</h2>#}
{##}
{#                        <p class="post-meta">#}
{#                            By <a class="post-author" href="#">Andrew Wooldridge</a> under <a class="post-category post-category-yui" href="#">YUI</a>#}
{#                        </p>#}
{#                    </header>#}
{##}
{#                    <div class="post-description">#}
{#                        <p>#}
{#                            We are happy to announce the release of YUI 3.10.2! You can find it now on the Yahoo! CDN, download it directly, or pull it in via npm. We’ve also updated the YUI Library website with the latest documentation.#}
{#                        </p>#}
{#                    </div>#}
{#                </section>#}
            </div>

            <div class="footer">
                <div class="pure-menu pure-menu-horizontal">
                    <ul>
                        <li class="pure-menu-item"><a href="" class="pure-menu-link">About</a></li>
                        <li class="pure-menu-item"><a href="" class="pure-menu-link">Twitter</a></li>
                        <li class="pure-menu-item"><a href="" class="pure-menu-link">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>



</body>
</html>

templates/blog/content.html
{% extends 'base.html' %}
{% load static %}
{% block personResource %}
    <title>文章内容</title>
    <script type="text/javascript" src="{% static 'js/content.js' %}"></script>


{% endblock %}



{% block content %}
    <div style="padding-bottom: 60px; border-bottom: 2px solid darkcyan">
    <h3>{{ article.title }}    <a  style="float:right;" href="{% url 'blog:publish' article.id %}">编辑</a></h3>

    <h4>{{ article.author }}</h4>
    <h5>{{ article.create_time }}</h5>
    <p>{{ article.content }}

    </p>
    <form class="pure-form" action="{% url 'blog:content' article.id %}" method="post">
        {% csrf_token %}
        <input class="pure-input-2-3" type="text" name="comment" placeholder="说说您的看法吧">
        <button type="submit" class="pure-button pure-button-primary">评论</button>
    </form>
    </div>
    <h3>文章评论</h3>
    {% for comment in comments %}
        <div style="border: 1px solid orange;padding-left:20px;border-radius: 10px ;margin-bottom:10px ">
            <p style="margin-bottom: 0px">{{ comment.username }}&nbsp;&nbsp;回复&nbsp;&nbsp;{{ comment.parent.username }}</p>
            <p style="" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ comment.comment }}</p>
            <h6 style="float: right;margin: 0px ;padding: 0px">{{ comment.create_time }}</h6>

            <p style="font-size: 10px;color: orange ;width: 30px" class="preply">回复</p>


            <div class="reply" style="display: none">

                <form class="pure-form" action="{% url 'blog:content' article.id comment.id %}" method="post">
                    {% csrf_token %}
                    <input id="reply" class="pure-input-1-5" type="text" name="comment" placeholder="说说您的看法吧">
                    <button type="submit" class=" pure-button pure-button-primary">回复</button>
                </form>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/blog/edit.html
{% extends "base.html" %}

{%block content %}
    <div class="container">
        <form method="POST" action="/blog/edit/">
            {% csrf_token %}
            <div>
                <input type="text" name="title" value="{{article.title}}">
            </div>
            <div>
                <textarea name="content" rows="20" cols="100">{{article.content}}</textarea>
            </div>
            <input type="hidden" name="aid" value="{{article.id}}">
            <input type="submit" name="提交">
        </form>
    </div>
{%endblock%}

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block personResource %}
    <title>首页</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


{% endblock %}



{% block content %}
    {% for article in articles %}
        <div class="posts">
            <h1 class="content-subhead">文章</h1>

            <!-- A single blog post -->
            <section class="post">
                <header class="post-header">
                    <img width="48" height="48" alt="Tilo Mitra&#x27;s avatar" class="post-avatar"
                         src="{% static 'images/default.jpg' %}">

                    <h3 class="post-title"><a href="{% url 'blog:content' article.id %}">{{ article.title }}</a></h3>

                    <p class="post-meta">
                        <a href="#" class="post-author">{{ article.author }}</a> 发表于 <a
                            class="post-category post-category-design" href="#">{{ article.create_time }}</a>
                        {#                            By <a href="#" class="post-author">{{ article.author }}</a> 发表于 <a class="post-category post-category-design" href="#">CSS</a> <a class="post-category post-category-pure" href="#">Pure</a>#}
                    </p>
                </header>

                <div class="post-description">
                    <p>
                        {{ article.content }}
                    </p>
                </div>
            </section>
        </div>
    {% endfor %}
    <nav  aria-label="Page navigation">
        <ul class="pagination" style="float: left">
            {% if articles.has_previous %}
            <li>
                <a href="?page={{ articles.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
                {% for pg in pages_range %}

                    {% if articles.num == pg %}
                        <li class="active" style="font-size: 20px"><a href="?page={{pg}}">{{ articles.number}}</a></li>
                    {% else %}
                        <li><a href="?page={{pg}}">{{pg}}</a></li>

                    {% endif %}

                {% endfor %}

            {% if articles.has_next %}
            <li>
                <a href="?page={{ articles.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
        {% endif %}
    </nav>

{% endblock %}

templates/blog/publish.html
{% extends 'base.html' %}
{% load static %}
{% block personResource %}
    <title>发表文章</title>


{% endblock %}



{%block content%}
    <form class="pure-form" action="{% url 'blog:publish' %}" method="post">
    {%csrf_token%}
    <fieldset class="pure-group">
        <input type="text" class="pure-input-1" name="title" placeholder="A title" value="{{ article.title }}">
        <textarea style="height: 200px;" class="pure-input-1" name="content" placeholder="Textareas work too">{{ article.content }}</textarea>
    </fieldset>
    <input type="hidden" name="aid" value="{{article.id}}">
    <button type="submit" class="pure-button pure-input-1-5 pure-button-primary">发表</button>
</form>
{% endblock %}

templates/blog/search.html
{% extends 'base.html' %}
{% load static %}
{% block personResource %}
    <title>首页</title>



{% endblock %}



{%block content%}
    {% for article in articles %}
<div class="posts">
                <h1 class="content-subhead">文章</h1>

                <!-- A single blog post -->
                <section class="post">
                    <header class="post-header">
                        <img width="48" height="48" alt="Tilo Mitra&#x27;s avatar" class="post-avatar" src="{% static 'images/default.jpg' %}">

                        <h3 class="post-title"><a href="{% url 'blog:content' article.id  %}">{{ article.title }}</a></h3>

                        <p class="post-meta">
                            <a href="#" class="post-author">{{ article.author }}</a> 发表于 <a class="post-category post-category-design" href="#">{{ article.create_time }}</a>
{#                            By <a href="#" class="post-author">{{ article.author }}</a> 发表于 <a class="post-category post-category-design" href="#">CSS</a> <a class="post-category post-category-pure" href="#">Pure</a>#}
                        </p>
                    </header>

                    <div class="post-description">
                        <p>
                            {{ article.content }}
                        </p>
                    </div>
                </section>
            </div>
    {% endfor %}
{% endblock %}

templates/blog/sort.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试排序</title>
</head>
<body>
<ul>
    {% for article,c in article_count %}
       <li> {{ article.title }}点击量:{{ c }}
        </li>

    {% endfor %}

</ul>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    我是注册页面
    <form class="form" action="{% url 'user:register' %}" method="post">
    {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        {% endfor %}
        <button type="submit" >注册</button>
    </form>

</body>
</html>